Repository catenax/tractusx, pull requests merged in 2021-09, with the labels that each got.

#1 Feature CAX-1/CXMVP-23 Sample Digital Twin & Semantic Hub Frontend (Sprint1)
  infrastructure/manifests/portal-ingress.yaml
  infrastructure/manifests/portal-loadbalancer.yaml
  infrastructure/manifests/portal.yaml
  infrastructure/pipelines/.gitignore
  portal/code/tractus-x-portal/.env
  portal/code/tractus-x-portal/Dockerfile.develop
  portal/code/tractus-x-portal/README.md
  portal/code/tractus-x-portal/package-lock.json
  portal/code/tractus-x-portal/package.json
  portal/code/tractus-x-portal/public/semantics/circular_economy.json
  portal/code/tractus-x-portal/public/semantics/circular_economy.ttl
  portal/code/tractus-x-portal/public/semantics/circular_economy.yaml
  portal/code/tractus-x-portal/public/semantics/circular_economy_en.html
  portal/code/tractus-x-portal/public/semantics/circular_economy_en.png
  portal/code/tractus-x-portal/public/semantics/circular_economy_schema.json
  portal/code/tractus-x-portal/public/semantics/dataspace.svg
  portal/code/tractus-x-portal/public/semantics/gdpm.json
  portal/code/tractus-x-portal/public/semantics/gdpm.ttl
  portal/code/tractus-x-portal/public/semantics/gdpm.yaml
  portal/code/tractus-x-portal/public/semantics/gdpm_en.html
  portal/code/tractus-x-portal/public/semantics/gdpm_en.png
  portal/code/tractus-x-portal/public/semantics/gdpm_schema.json
  portal/code/tractus-x-portal/public/semantics/traceability.json
  portal/code/tractus-x-portal/public/semantics/traceability.ttl
  portal/code/tractus-x-portal/public/semantics/traceability.yaml
  portal/code/tractus-x-portal/public/semantics/traceability_en.html
  portal/code/tractus-x-portal/public/semantics/traceability_en.png
  portal/code/tractus-x-portal/public/semantics/traceability_schema.json
  portal/code/tractus-x-portal/src/App.tsx
  portal/code/tractus-x-portal/src/components/appdetail.tsx
  portal/code/tractus-x-portal/src/components/apps/dataupload.tsx
  portal/code/tractus-x-portal/src/components/apps/dataupload2.tsx
  portal/code/tractus-x-portal/src/components/digitaltwins.tsx
  portal/code/tractus-x-portal/src/components/header.tsx
  portal/code/tractus-x-portal/src/components/home.tsx
  portal/code/tractus-x-portal/src/components/lists/descriptionlist.tsx
  portal/code/tractus-x-portal/src/components/navigation/backlink.tsx
  portal/code/tractus-x-portal/src/components/newsemanticmodel.tsx
  portal/code/tractus-x-portal/src/components/semantichub.tsx
  portal/code/tractus-x-portal/src/components/semanticmodeldetail.tsx
  portal/code/tractus-x-portal/src/components/vocabulary.tsx
  portal/code/tractus-x-portal/src/helpers/adalConfig.ts
  portal/code/tractus-x-portal/src/helpers/utils.ts
  portal/code/tractus-x-portal/src/index.tsx
  portal/code/tractus-x-portal/src/styles/App.css
  portal/code/tractus-x-portal/src/styles/index.css
  portal/code/tractus-x-portal/src/styles/reset.css
  portal/code/tractus-x-portal/tsi.env
Labels: Target:Portfolio

#4 Feature CAX-1/CXMVP-23 Sample Digital Twin & Semantic Hub Frontend (Sprint1)
  infrastructure/manifests/portal-ingress.yaml
  infrastructure/manifests/portal-loadbalancer.yaml
  infrastructure/manifests/portal.yaml
  infrastructure/pipelines/.gitignore
  portal/code/tractus-x-portal/.env
  portal/code/tractus-x-portal/Dockerfile.develop
  portal/code/tractus-x-portal/README.md
  portal/code/tractus-x-portal/package-lock.json
  portal/code/tractus-x-portal/package.json
  portal/code/tractus-x-portal/public/semantics/circular_economy.json
  portal/code/tractus-x-portal/public/semantics/circular_economy.ttl
  portal/code/tractus-x-portal/public/semantics/circular_economy.yaml
  portal/code/tractus-x-portal/public/semantics/circular_economy_en.html
  portal/code/tractus-x-portal/public/semantics/circular_economy_en.png
  portal/code/tractus-x-portal/public/semantics/circular_economy_schema.json
  portal/code/tractus-x-portal/public/semantics/dataspace.svg
  portal/code/tractus-x-portal/public/semantics/gdpm.json
  portal/code/tractus-x-portal/public/semantics/gdpm.ttl
  portal/code/tractus-x-portal/public/semantics/gdpm.yaml
  portal/code/tractus-x-portal/public/semantics/gdpm_en.html
  portal/code/tractus-x-portal/public/semantics/gdpm_en.png
  portal/code/tractus-x-portal/public/semantics/gdpm_schema.json
  portal/code/tractus-x-portal/public/semantics/traceability.json
  portal/code/tractus-x-portal/public/semantics/traceability.ttl
  portal/code/tractus-x-portal/public/semantics/traceability.yaml
  portal/code/tractus-x-portal/public/semantics/traceability_en.html
  portal/code/tractus-x-portal/public/semantics/traceability_en.png
  portal/code/tractus-x-portal/public/semantics/traceability_schema.json
  portal/code/tractus-x-portal/src/App.tsx
  portal/code/tractus-x-portal/src/components/appdetail.tsx
  portal/code/tractus-x-portal/src/components/apps/dataupload.tsx
  portal/code/tractus-x-portal/src/components/apps/dataupload2.tsx
  portal/code/tractus-x-portal/src/components/digitaltwins.tsx
  portal/code/tractus-x-portal/src/components/header.tsx
  portal/code/tractus-x-portal/src/components/home.tsx
  portal/code/tractus-x-portal/src/components/lists/descriptionlist.tsx
  portal/code/tractus-x-portal/src/components/navigation/backlink.tsx
  portal/code/tractus-x-portal/src/components/newsemanticmodel.tsx
  portal/code/tractus-x-portal/src/components/semantichub.tsx
  portal/code/tractus-x-portal/src/components/semanticmodeldetail.tsx
  portal/code/tractus-x-portal/src/components/vocabulary.tsx
  portal/code/tractus-x-portal/src/helpers/adalConfig.ts
  portal/code/tractus-x-portal/src/helpers/utils.ts
  portal/code/tractus-x-portal/src/index.tsx
  portal/code/tractus-x-portal/src/styles/App.css
  portal/code/tractus-x-portal/src/styles/index.css
  portal/code/tractus-x-portal/src/styles/reset.css
  portal/code/tractus-x-portal/tsi.env
Labels: Target:Staging

#6 Adjust Java code generation
  semantics/openapi.yaml
  semantics/pom.xml
  semantics/src/main/java/net/catenax/semantics/Application.java
  semantics/src/main/java/net/catenax/semantics/hub/ModelsService.java
  semantics/src/main/java/net/catenax/semantics/hub/SemanticHub.java
  semantics/src/main/java/net/catenax/semantics/hub/api/ApiUtil.java
  semantics/src/main/java/net/catenax/semantics/hub/api/ModelsApi.java
  semantics/src/main/java/net/catenax/semantics/hub/api/ModelsApiController.java
  semantics/src/main/java/net/catenax/semantics/hub/api/model/Model.java
  semantics/src/main/java/net/catenax/semantics/hub/api/model/NewModel.java
  semantics/src/main/java/net/catenax/semantics/hub/service/Model.java
  semantics/src/main/java/net/catenax/semantics/hub/service/ModelBean.java
  semantics/src/main/java/net/catenax/semantics/hub/service/SemanticHubService.java
  semantics/src/main/java/net/catenax/semantics/hub/service/SemanticHubServiceImpl.java
  semantics/src/main/resources/application.properties
  semantics/src/test/java/net/catenax/semantics/BaseSemanticModelTest.java
Labels: Target:Feature

#3 Feature CAX-1/CXMVP-18 Semantic Layer incl. Hub (Sprint1)
  .gitignore
  infrastructure/manifests/semantics-ingress.yaml
  infrastructure/manifests/semantics.yaml
  infrastructure/pipelines/script_deployment.sh
  semantics/Dockerfile
  semantics/README.md
  semantics/SMDA.drawio
  semantics/openapi.yaml
  semantics/pom.xml
  semantics/run_local.sh
  semantics/src/main/java/net/catenax/semantics/hub/ModelsService.java
  semantics/src/main/java/net/catenax/semantics/hub/SemanticHub.java
  semantics/src/main/resources/application.properties
  semantics/src/main/resources/models/SemanticHub.oai.json
  semantics/src/main/resources/models/SemanticHub.ttl
  semantics/src/main/resources/models/SemanticHub_en.png
  semantics/src/main/resources/models/TwinRegistry.ttl
  semantics/src/test/java/net/catenax/semantics/BaseSemanticModelTest.java
  semantics/src/test/java/net/catenax/semantics/TestSemanticHubModel.java
  semantics/src/test/java/net/catenax/semantics/TestTwinRegistryModel.java
Labels: Target:Portfolio

#7 Feature CAX-1/CXMVP-18 Semantic Layer incl. Hub (Sprint1)
  .gitignore
  infrastructure/manifests/semantics-ingress.yaml
  infrastructure/manifests/semantics.yaml
  infrastructure/pipelines/script_deployment.sh
  semantics/Dockerfile
  semantics/README.md
  semantics/SMDA.drawio
  semantics/openapi.yaml
  semantics/pom.xml
  semantics/run_local.sh
  semantics/src/main/java/net/catenax/semantics/hub/ModelsService.java
  semantics/src/main/java/net/catenax/semantics/hub/SemanticHub.java
  semantics/src/main/resources/application.properties
  semantics/src/main/resources/models/SemanticHub.oai.json
  semantics/src/main/resources/models/SemanticHub.ttl
  semantics/src/main/resources/models/SemanticHub_en.png
  semantics/src/main/resources/models/TwinRegistry.ttl
  semantics/src/test/java/net/catenax/semantics/BaseSemanticModelTest.java
  semantics/src/test/java/net/catenax/semantics/TestSemanticHubModel.java
  semantics/src/test/java/net/catenax/semantics/TestTwinRegistryModel.java
Labels: Target:Staging

#61 Feature/CAX-1-semantics@CXMVP-63-semantic-architecture Terraform dev042
  .github/workflows/partsrelationshipservice-deploy.yml
  .github/workflows/partsrelationshipservice.yml
  .github/workflows/terraform.yml
  coreservices/partsrelationshipservice/.gitignore
  coreservices/partsrelationshipservice/Dockerfile
  coreservices/partsrelationshipservice/cd/applicationinsights.json
  coreservices/partsrelationshipservice/cd/build_and_push_docker.sh
  coreservices/partsrelationshipservice/ci/checkstyle-suppressions.xml
  coreservices/partsrelationshipservice/ci/checkstyle.xml
  coreservices/partsrelationshipservice/ci/pmd-rules.xml
  coreservices/partsrelationshipservice/ci/spotbugs-excludes.xml
  coreservices/partsrelationshipservice/helm/prs/.helmignore
  coreservices/partsrelationshipservice/helm/prs/Chart.yaml
  coreservices/partsrelationshipservice/helm/prs/templates/deployment.yaml
  coreservices/partsrelationshipservice/helm/prs/templates/ingress.yaml
  coreservices/partsrelationshipservice/helm/prs/templates/secrets.yaml
  coreservices/partsrelationshipservice/helm/prs/templates/service.yaml
  coreservices/partsrelationshipservice/helm/prs/values.yaml
  coreservices/partsrelationshipservice/lombok.config
  coreservices/partsrelationshipservice/mvnw
  coreservices/partsrelationshipservice/mvnw.cmd
  coreservices/partsrelationshipservice/pom.xml
  coreservices/partsrelationshipservice/src/main/java/net/catenax/prs/PrsApplication.java
  coreservices/partsrelationshipservice/src/main/java/net/catenax/prs/controllers/PrsController.java
  coreservices/partsrelationshipservice/src/main/resources/application.yml
  coreservices/partsrelationshipservice/src/test/java/net/catenax/prs/PrsApplicationTests.java
  coreservices/partsrelationshipservice/src/test/java/net/catenax/prs/controllers/PrsControllerTests.java
  coreservices/partsrelationshipservice/terraform/README.md
  coreservices/partsrelationshipservice/terraform/main.tf
  coreservices/partsrelationshipservice/terraform/modules/application-insights/main.tf
  coreservices/partsrelationshipservice/terraform/modules/application-insights/output.tf
  coreservices/partsrelationshipservice/terraform/modules/application-insights/variables.tf
  coreservices/partsrelationshipservice/terraform/modules/eventhub/main.tf
  coreservices/partsrelationshipservice/terraform/modules/eventhub/outputs.tf
  coreservices/partsrelationshipservice/terraform/modules/eventhub/variables.tf
  coreservices/partsrelationshipservice/terraform/modules/eventhubs_namespace/main.tf
  coreservices/partsrelationshipservice/terraform/modules/eventhubs_namespace/outputs.tf
  coreservices/partsrelationshipservice/terraform/modules/eventhubs_namespace/variables.tf
  coreservices/partsrelationshipservice/terraform/modules/postgresql/main.tf
  coreservices/partsrelationshipservice/terraform/modules/postgresql/outputs.tf
  coreservices/partsrelationshipservice/terraform/modules/postgresql/variables.tf
  coreservices/partsrelationshipservice/terraform/outputs.tf
  coreservices/partsrelationshipservice/terraform/variables.tf
  coreservices/partsrelationshipservice/terraform/versions.tf
  infrastructure/manifests/environment.sh
  infrastructure/terraform/README.md
  infrastructure/terraform/cluster-issuer.yaml
  infrastructure/terraform/environments/dev042.tfvars
  infrastructure/terraform/environments/int.sh
  infrastructure/terraform/main.tf
  infrastructure/terraform/modules/aks/main.tf
  infrastructure/terraform/modules/aks/variables.tf
  infrastructure/terraform/provider.tf
  infrastructure/terraform/roleassigner.json
  infrastructure/terraform/variables.tf
  infrastructure/terraform/versions.tf
Labels: Target:Feature, Portfolio:Semantic Layer

#62 Feature/CAX-12-devops@CXMVP-113-terraform
  .github/workflows/terraform.yml
  infrastructure/manifests/environment.sh
  infrastructure/terraform/README.md
  infrastructure/terraform/cluster-issuer.yaml
  infrastructure/terraform/environments/dev001.tfvars
  infrastructure/terraform/environments/dev002.tfvars
  infrastructure/terraform/environments/dev042.tfvars
  infrastructure/terraform/environments/int.sh
  infrastructure/terraform/environments/int.tfvars
  infrastructure/terraform/environments/prod.tfvars
  infrastructure/terraform/main.tf
  infrastructure/terraform/modules/aks/main.tf
  infrastructure/terraform/modules/aks/variables.tf
  infrastructure/terraform/provider.tf
  infrastructure/terraform/roleassigner.json
  infrastructure/terraform/variables.tf
  infrastructure/terraform/versions.tf
Labels: Target:Portfolio, Portfolio:Devops

#63 Feature/cax 1 semantics@cxmvp 18 semantic hub db connection
  semantics/openapi.yaml
  semantics/pom.xml
  semantics/src/main/java/net/catenax/semantics/hub/ModelsService.java
  semantics/src/main/java/net/catenax/semantics/hub/persistence/ModelRepository.java
  semantics/src/main/java/net/catenax/semantics/hub/persistence/PersistenceLayer.java
  semantics/src/main/java/net/catenax/semantics/hub/persistence/RDBMSPersistence.java
  semantics/src/main/java/net/catenax/semantics/hub/persistence/mapper/SemanticModelMapper.java
  semantics/src/main/java/net/catenax/semantics/hub/persistence/model/ModelEntity.java
  semantics/src/main/resources/application.properties
Labels: Target:Staging, Portfolio:Semantic Layer

#70 Feature/CAX-12-devops Add by-need App registration and database creation
  .github/workflows/terraform.yml
  infrastructure/terraform/main.tf
Labels: Target:Feature, Portfolio:Semantic Layer, Portfolio:Devops

#72 Feature/CAX-12-devops@CXMVP-133-terraform Debug the ingress behaviour under kubernetes >1.18
  .github/workflows/terraform.yml
  infrastructure/terraform/cluster-issuer.yaml
  infrastructure/terraform/main.tf
Labels: Target:Feature, Portfolio:Semantic Layer

#74 Feature/cax 12 devops@cxmvp 113 terraform
  .github/workflows/terraform.yml
  coreservices/partsrelationshipservice/src/main/java/net/catenax/prs/PrsApplication.java
  coreservices/partsrelationshipservice/src/main/java/net/catenax/prs/controllers/PrsController.java
  coreservices/partsrelationshipservice/src/main/resources/application.yml
  coreservices/partsrelationshipservice/src/test/java/net/catenax/prs/PrsApplicationTests.java
  coreservices/partsrelationshipservice/src/test/java/net/catenax/prs/controllers/PrsControllerTests.java
  infrastructure/manifests/environment.sh
  infrastructure/terraform/README.md
  infrastructure/terraform/cluster-issuer.yaml
  infrastructure/terraform/environments/dev001.tfvars
  infrastructure/terraform/environments/dev002.tfvars
  infrastructure/terraform/environments/dev003.tfvars
  infrastructure/terraform/environments/dev042.tfvars
  infrastructure/terraform/environments/int.sh
  infrastructure/terraform/environments/int.tfvars
  infrastructure/terraform/environments/prod.tfvars
  infrastructure/terraform/main.tf
  infrastructure/terraform/modules/aks/main.tf
  infrastructure/terraform/modules/aks/variables.tf
  infrastructure/terraform/modules/variables/inputs.tf
  infrastructure/terraform/modules/variables/main.tf
  infrastructure/terraform/modules/variables/outputs.tf
  infrastructure/terraform/outputs.tf
  infrastructure/terraform/provider.tf
  infrastructure/terraform/roleassigner.json
  infrastructure/terraform/variables.tf
  infrastructure/terraform/versions.tf
Labels: Target:Staging, Portfolio:Devops

#76 https://jira.catena-x.net/browse/CATART0PO4-139
  .github/workflows/terraform.yml
  infrastructure/terraform/versions.tf
Labels: Target:Staging, Portfolio:Semantic Layer

#85 Solution for https://jira.catena-x.net/browse/CATART0PO4-139
  .github/workflows/terraform.yml
  infrastructure/terraform/environments/dev004.tfvars
  infrastructure/terraform/kube_admin_config.json
  infrastructure/terraform/provider.tf
  infrastructure/terraform/state.json
  infrastructure/terraform/variables.tf
Labels: Target:Staging, Portfolio:Devops

#84 Feature/cax onborading UI
  portal/code/tractus-x-portal/.gitignore
  portal/code/tractus-x-portal/package-lock.json
  portal/code/tractus-x-portal/src/components/header.tsx
  portal/code/tractus-x-portal/src/components/home.tsx
  portal/code/tractus-x-portal/src/components/onboarding.tsx
  portal/code/tractus-x-portal/src/components/semanticmodeldetail.tsx
  portal/code/tractus-x-portal/src/styles/App.css
Labels: Portfolio:onboarding

#89 Feature/cax onborading UI
  portal/code/tractus-x-portal/src/components/onboarding.tsx
Labels: Portfolio:onboarding
