Repository catenax/tractusx, pull requests merged in 2022-04, with the labels that each got.

#514 fix: Bug in edc-specific adapter startup code. Do not try to register cont…
  semantics/framework/src/main/java/net/catenax/semantics/framework/ids/BaseConnector.java
Labels: bug, Target:Staging, Portfolio:Semantic Layer

#522 That file was git ignored when merging branches. Sample backend servi…
  eclipsedataspaceconnector/api-wrapper/launchers/provider-backend-service/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
Labels: bug

#483 FIX/adjust env files
  portal/code/tractus-x-portal/.env
  portal/code/tractus-x-portal/dev042.env
  portal/code/tractus-x-portal/devtsi.env
  portal/code/tractus-x-portal/int.env
Labels: Target:Staging, Portfolio:Semantic Layer
